# use an existing docker image as a base
FROM alpine


# download and install a dependency
RUN apk add --update redis
RUN apk add --update gcc


# tell teh image what to do as it starts as a container

CMD ["redis-server"]